### PR TITLE
Detect duplicate resources (same [API version, kind, namespace, name])

### PR DESCRIPTION
**Pull request by AndiDog**
Introduces `-n/--default-namespace` to specify which namespace a resource would be assigned if none is explicitly defined in the manifest. Exhaustively tested.

### CODE REVIEW

**Comment by garethr** [comment]
Thanks, useful suggestion. Would you be able to rebase this against the latest master and I'll get into the next release.

**Comment by AndiDog** [comment]
I rebased and successfully ran `make test` again

**Comment by m0un10** [comment]
This just broke our pipeline when we upgraded to 0.16. Would you be open to a new PR which introduces `--ignore-duplicate-resources  Skip validation for duplication resources` ?

Our use case is that we pipe a whole bunch of different test cases to `kubeval` to make sure our templating solution doesn't have a bug introduces regarding kubernetes semantics. Since we don't actually deploy our test manifests we don't care about duplicates and in fact we expect them as we have many different tests and some use the same names.

**Comment by carlossg** [comment]
sounds good

**Pull request merged**
