### PR TITLE
detect Helm source template from comments

### PR DESCRIPTION
**Pull request by glb**
Helm provides the name of the source template in a comment at the top
of each document, for example:

```yaml
# Source: chart/templates/kind.yaml
...
```

It is helpful to have this filename in the results when we can detect it.

### CODE REVIEW

**Comment by glb** [comment]
🤔 I'm not sure why GitHub shows that I've got conflicts here; I'm 1 commit ahead of `instrumenta:master` and `git diff upstream/master..` doesn't show anything other than my changes.

**Comment by garethr** [comment]
Thanks for the submission. Sounds like a great idea. I'll look at resolving the conflict soon all being well.

**Comment by glb** [comment]
Thanks @garethr! I took another look and found out I'd somehow set upstream to the wrong location. Rebased to current `master`.

**Comment by garethr** [comment]
Thanks for this. I've just merged in with a number of other changes, and updated the acceptance tests accordingly. I'll get the docs updated with the latest batch of changes and then get a new release out.

**Pull request merged**
