### PR TITLE
Add new feature flag to pass content of a file directly

### PR DESCRIPTION
**Pull request by YoshiMan**
I faced the problem, that i wanted to use your tool inside a docker-in-docker environment, so i was not able to mount a deployment.yaml.
So i created the possibility to pass the file content.

### CODE REVIEW

**Comment by YoshiMan** [comment]
Hey @garethr 
how about this merge request.
What do you think? Any problems to merge or should i change anything?

**Comment by garethr** [comment]
Is there a reason why using stdin didn't work in your case? ie. 

```
cat your-file.yaml | kubeval
```

**Comment by bacongobbler** [comment]
pinging @YoshiMan; any response on the above question? kubeval accepts content on stdin so `cat myfilename | kubeval` should work as @garethr pointed out. Does that work for your use case?

**Comment by YoshiMan** [comment]
Hey
As I said I'm using this in a docker in docker environment, which means our build server runs in a docker container and I want to use kubeval as a docker container. So this means I can not mount a file from the build server into the kubeval container.
So I need to pass the content of the file as argument to the kubeval container.

**Comment by tholok97** [comment]
@YoshiMan It is possible to pass in your `deployment.yaml` file to the docker container without mounting using the syntax @garethr used. The thing to remember is to pass `-i` to `docker run`. Examples:
```bash
# through pipe
cat deployment.yaml | docker run -i garethr/kubeval:0.8.1 --strict

# through redirect (which might be preferred? "Unnecessary" call to `cat` is avoided)
docker run -i garethr/kubeval:0.8.1 --strict < deployment.yaml
```

Reference: https://stackoverflow.com/questions/35688407/piping-a-file-into-docker-run

# BUT

Notice that I passed a flag `--strict`. As the Dockerfile has `CMD ["--help"]` you are forced to pass some flag (`--` also seems to work fine) to avoid `kubeval --help` to be executed.

*Should this be fixed?*

**Comment by YoshiMan** [comment]
Yeah @tholok97
Thanks a lot. This works for me. 😘
Pity about my work for the pull request.

**Pull request closed without merging**
